-- ============================================================
-- Plately — Migration 012d: Full Cyrillic Uzbek Translations
-- All 278 ingredients
-- ============================================================

-- ── Vegetables ──
UPDATE public.ingredients SET display_name_uz_cyrl = 'Артишок'             WHERE canonical_name = 'artichoke';
UPDATE public.ingredients SET display_name_uz_cyrl = 'Қушқўнмас'           WHERE canonical_name = 'asparagus';
UPDATE public.ingredients SET display_name_uz_cyrl = 'Бамбук новдаси'      WHERE canonical_name = 'bamboo_shoots';
UPDATE public.ingredients SET display_name_uz_cyrl = 'Униб чиққан ловия'   WHERE canonical_name = 'bean_sprouts';
UPDATE public.ingredients SET display_name_uz_cyrl = 'Лавлаги'             WHERE canonical_name = 'beet';
UPDATE public.ingredients SET display_name_uz_cyrl = 'Болгар қалампири'    WHERE canonical_name = 'bell_pepper';
UPDATE public.ingredients SET display_name_uz_cyrl = 'Брокколи'            WHERE canonical_name = 'broccoli';
UPDATE public.ingredients SET display_name_uz_cyrl = 'Брюссел карамчаси'   WHERE canonical_name = 'brussels_sprouts';
UPDATE public.ingredients SET display_name_uz_cyrl = 'Карам'               WHERE canonical_name = 'cabbage';
UPDATE public.ingredients SET display_name_uz_cyrl = 'Сабзи'              WHERE canonical_name = 'carrot';
UPDATE public.ingredients SET display_name_uz_cyrl = 'Гулкарам'            WHERE canonical_name = 'cauliflower';
UPDATE public.ingredients SET display_name_uz_cyrl = 'Селдерей'            WHERE canonical_name = 'celery';
UPDATE public.ingredients SET display_name_uz_cyrl = 'Маккажўхори'         WHERE canonical_name = 'corn';
UPDATE public.ingredients SET display_name_uz_cyrl = 'Бодринг'            WHERE canonical_name = 'cucumber';
UPDATE public.ingredients SET display_name_uz_cyrl = 'Бақлажон'            WHERE canonical_name = 'eggplant';
UPDATE public.ingredients SET display_name_uz_cyrl = 'Укроп'               WHERE canonical_name = 'dill';
UPDATE public.ingredients SET display_name_uz_cyrl = 'Саримсоқ'           WHERE canonical_name = 'garlic';
UPDATE public.ingredients SET display_name_uz_cyrl = 'Занжабил'            WHERE canonical_name = 'ginger';
UPDATE public.ingredients SET display_name_uz_cyrl = 'Кўк пиёз'           WHERE canonical_name = 'green_onion';
UPDATE public.ingredients SET display_name_uz_cyrl = 'Кўк турп'            WHERE canonical_name = 'green_radish';
UPDATE public.ingredients SET display_name_uz_cyrl = 'Кейл'               WHERE canonical_name = 'kale';
UPDATE public.ingredients SET display_name_uz_cyrl = 'Порра'               WHERE canonical_name = 'leek';
UPDATE public.ingredients SET display_name_uz_cyrl = 'Кўкмат'              WHERE canonical_name = 'lettuce';
UPDATE public.ingredients SET display_name_uz_cyrl = 'Қўзиқорин'           WHERE canonical_name = 'mushroom';
UPDATE public.ingredients SET display_name_uz_cyrl = 'Бамия'               WHERE canonical_name = 'okra';
UPDATE public.ingredients SET display_name_uz_cyrl = 'Пиёз'               WHERE canonical_name = 'onion';
UPDATE public.ingredients SET display_name_uz_cyrl = 'Петрушка'            WHERE canonical_name = 'parsley';
UPDATE public.ingredients SET display_name_uz_cyrl = 'Нўхат'               WHERE canonical_name = 'peas';
UPDATE public.ingredients SET display_name_uz_cyrl = 'Картошка'           WHERE canonical_name = 'potato';
UPDATE public.ingredients SET display_name_uz_cyrl = 'Ошқовоқ'             WHERE canonical_name = 'pumpkin';
UPDATE public.ingredients SET display_name_uz_cyrl = 'Турп'                WHERE canonical_name = 'radish';
UPDATE public.ingredients SET display_name_uz_cyrl = 'Қизил карам'         WHERE canonical_name = 'red_cabbage';
UPDATE public.ingredients SET display_name_uz_cyrl = 'Шолғом'              WHERE canonical_name = 'turnip';
UPDATE public.ingredients SET display_name_uz_cyrl = 'Исмалоқ'            WHERE canonical_name = 'spinach';
UPDATE public.ingredients SET display_name_uz_cyrl = 'Татлимош'            WHERE canonical_name = 'sweet_potato';
UPDATE public.ingredients SET display_name_uz_cyrl = 'Помидор'            WHERE canonical_name = 'tomato';
UPDATE public.ingredients SET display_name_uz_cyrl = 'Қовоқча'             WHERE canonical_name = 'zucchini';
UPDATE public.ingredients SET display_name_uz_cyrl = 'Шалот'               WHERE canonical_name = 'shallot';
UPDATE public.ingredients SET display_name_uz_cyrl = 'Укроп'               WHERE canonical_name = 'fennel';
UPDATE public.ingredients SET display_name_uz_cyrl = 'Халапено'            WHERE canonical_name = 'jalapeno';
UPDATE public.ingredients SET display_name_uz_cyrl = 'Пак-чой'             WHERE canonical_name = 'bok_choy';
UPDATE public.ingredients SET display_name_uz_cyrl = 'Сув седанаси'        WHERE canonical_name = 'watercress';
UPDATE public.ingredients SET display_name_uz_cyrl = 'Дайкон'              WHERE canonical_name = 'daikon';
UPDATE public.ingredients SET display_name_uz_cyrl = 'Сариқ пиёз'         WHERE canonical_name = 'yellow_onion';
UPDATE public.ingredients SET display_name_uz_cyrl = 'Қизил пиёз'         WHERE canonical_name = 'red_onion';
UPDATE public.ingredients SET display_name_uz_cyrl = 'Аччиқ қалампир'     WHERE canonical_name = 'chili_pepper';

-- ── Fruits ──
UPDATE public.ingredients SET display_name_uz_cyrl = 'Олма'               WHERE canonical_name = 'apple';
UPDATE public.ingredients SET display_name_uz_cyrl = 'Авокадо'            WHERE canonical_name = 'avocado';
UPDATE public.ingredients SET display_name_uz_cyrl = 'Банан'              WHERE canonical_name = 'banana';
UPDATE public.ingredients SET display_name_uz_cyrl = 'Кўк гилос'          WHERE canonical_name = 'blueberry';
UPDATE public.ingredients SET display_name_uz_cyrl = 'Гилос'              WHERE canonical_name = 'cherry';
UPDATE public.ingredients SET display_name_uz_cyrl = 'Кокос'               WHERE canonical_name = 'coconut';
UPDATE public.ingredients SET display_name_uz_cyrl = 'Узум'                WHERE canonical_name = 'grape';
UPDATE public.ingredients SET display_name_uz_cyrl = 'Грейпфрут'           WHERE canonical_name = 'grapefruit';
UPDATE public.ingredients SET display_name_uz_cyrl = 'Киви'                WHERE canonical_name = 'kiwi';
UPDATE public.ingredients SET display_name_uz_cyrl = 'Лимон'              WHERE canonical_name = 'lemon';
UPDATE public.ingredients SET display_name_uz_cyrl = 'Лайм'               WHERE canonical_name = 'lime';
UPDATE public.ingredients SET display_name_uz_cyrl = 'Манго'               WHERE canonical_name = 'mango';
UPDATE public.ingredients SET display_name_uz_cyrl = 'Қовун'               WHERE canonical_name = 'melon';
UPDATE public.ingredients SET display_name_uz_cyrl = 'Апелсин'            WHERE canonical_name = 'orange';
UPDATE public.ingredients SET display_name_uz_cyrl = 'Шафтоли'             WHERE canonical_name = 'peach';
UPDATE public.ingredients SET display_name_uz_cyrl = 'Нок'                 WHERE canonical_name = 'pear';
UPDATE public.ingredients SET display_name_uz_cyrl = 'Ананас'              WHERE canonical_name = 'pineapple';
UPDATE public.ingredients SET display_name_uz_cyrl = 'Ўрик'                WHERE canonical_name = 'plum';
UPDATE public.ingredients SET display_name_uz_cyrl = 'Анор'               WHERE canonical_name = 'pomegranate';
UPDATE public.ingredients SET display_name_uz_cyrl = 'Малина'              WHERE canonical_name = 'raspberry';
UPDATE public.ingredients SET display_name_uz_cyrl = 'Қулупнай'            WHERE canonical_name = 'strawberry';
UPDATE public.ingredients SET display_name_uz_cyrl = 'Тарвуз'              WHERE canonical_name = 'watermelon';
UPDATE public.ingredients SET display_name_uz_cyrl = 'Қуритилган ўрик'    WHERE canonical_name = 'dried_apricot';
UPDATE public.ingredients SET display_name_uz_cyrl = 'Майиз'              WHERE canonical_name = 'raisins';
UPDATE public.ingredients SET display_name_uz_cyrl = 'Беҳи'              WHERE canonical_name = 'quince';
UPDATE public.ingredients SET display_name_uz_cyrl = 'Фужи олма'           WHERE canonical_name = 'fuji_apple';
UPDATE public.ingredients SET display_name_uz_cyrl = 'Мандалина'           WHERE canonical_name = 'tangerine';
UPDATE public.ingredients SET display_name_uz_cyrl = 'Хурмо'               WHERE canonical_name = 'persimmon';
UPDATE public.ingredients SET display_name_uz_cyrl = 'Анжир'               WHERE canonical_name = 'fig';

-- ── Proteins ──
UPDATE public.ingredients SET display_name_uz_cyrl = 'Бекон'               WHERE canonical_name = 'bacon';
UPDATE public.ingredients SET display_name_uz_cyrl = 'Мол гўшти'          WHERE canonical_name = 'beef';
UPDATE public.ingredients SET display_name_uz_cyrl = 'Мол гўшти стейк'    WHERE canonical_name = 'beef_steak';
UPDATE public.ingredients SET display_name_uz_cyrl = 'Товуқ'              WHERE canonical_name = 'chicken';
UPDATE public.ingredients SET display_name_uz_cyrl = 'Товуқ кўкрак гўшти' WHERE canonical_name = 'chicken_breast';
UPDATE public.ingredients SET display_name_uz_cyrl = 'Товуқ сони'          WHERE canonical_name = 'chicken_thigh';
UPDATE public.ingredients SET display_name_uz_cyrl = 'Товуқ қаноти'        WHERE canonical_name = 'chicken_wing';
UPDATE public.ingredients SET display_name_uz_cyrl = 'Ўрдак'               WHERE canonical_name = 'duck';
UPDATE public.ingredients SET display_name_uz_cyrl = 'Тухум'              WHERE canonical_name = 'egg';
UPDATE public.ingredients SET display_name_uz_cyrl = 'Мол қиймаси'         WHERE canonical_name = 'ground_beef';
UPDATE public.ingredients SET display_name_uz_cyrl = 'Товуқ қиймаси'       WHERE canonical_name = 'ground_chicken';
UPDATE public.ingredients SET display_name_uz_cyrl = 'Чўчқа қиймаси'      WHERE canonical_name = 'ground_pork';
UPDATE public.ingredients SET display_name_uz_cyrl = 'Курка гўшти'         WHERE canonical_name = 'turkey';
UPDATE public.ingredients SET display_name_uz_cyrl = 'Жамбон'              WHERE canonical_name = 'ham';
UPDATE public.ingredients SET display_name_uz_cyrl = 'Қўй гўшти'         WHERE canonical_name = 'lamb';
UPDATE public.ingredients SET display_name_uz_cyrl = 'Қўй елкаси'         WHERE canonical_name = 'lamb_shoulder';
UPDATE public.ingredients SET display_name_uz_cyrl = 'Қўй оёғи'           WHERE canonical_name = 'lamb_leg';
UPDATE public.ingredients SET display_name_uz_cyrl = 'Қўй қовурғаси'      WHERE canonical_name = 'lamb_ribs';
UPDATE public.ingredients SET display_name_uz_cyrl = 'Думба ёғи'          WHERE canonical_name = 'lamb_fat';
UPDATE public.ingredients SET display_name_uz_cyrl = 'От гўшти'           WHERE canonical_name = 'horse_meat';
UPDATE public.ingredients SET display_name_uz_cyrl = 'Бедана'              WHERE canonical_name = 'quail';
UPDATE public.ingredients SET display_name_uz_cyrl = 'Чўчқа гўшти'        WHERE canonical_name = 'pork';
UPDATE public.ingredients SET display_name_uz_cyrl = 'Колбаса'             WHERE canonical_name = 'sausage';
UPDATE public.ingredients SET display_name_uz_cyrl = 'Тофу'                WHERE canonical_name = 'tofu';
UPDATE public.ingredients SET display_name_uz_cyrl = 'Темпе'               WHERE canonical_name = 'tempeh';
UPDATE public.ingredients SET display_name_uz_cyrl = 'Бузоқ гўшти'        WHERE canonical_name = 'veal';
UPDATE public.ingredients SET display_name_uz_cyrl = 'Қаттиқ тофу'        WHERE canonical_name = 'firm_tofu';
UPDATE public.ingredients SET display_name_uz_cyrl = 'Чўчқа гўшти бели'   WHERE canonical_name = 'pork_chop';
UPDATE public.ingredients SET display_name_uz_cyrl = 'Чўчқа гўшти бели'   WHERE canonical_name = 'pork_loin';

-- ── Dairy ──
UPDATE public.ingredients SET display_name_uz_cyrl = 'Сариёғ'             WHERE canonical_name = 'butter';
UPDATE public.ingredients SET display_name_uz_cyrl = 'Чеддар пишлоқ'      WHERE canonical_name = 'cheddar_cheese';
UPDATE public.ingredients SET display_name_uz_cyrl = 'Пишлоқ'            WHERE canonical_name = 'cheese';
UPDATE public.ingredients SET display_name_uz_cyrl = 'Қуюқ сут'            WHERE canonical_name = 'condensed_milk';
UPDATE public.ingredients SET display_name_uz_cyrl = 'Крем пишлоқ'         WHERE canonical_name = 'cream_cheese';
UPDATE public.ingredients SET display_name_uz_cyrl = 'Қаймоқ'             WHERE canonical_name = 'cream';
UPDATE public.ingredients SET display_name_uz_cyrl = 'Юқори ёғли қаймоқ'  WHERE canonical_name = 'heavy_cream';
UPDATE public.ingredients SET display_name_uz_cyrl = 'Сут'                WHERE canonical_name = 'milk';
UPDATE public.ingredients SET display_name_uz_cyrl = 'Мозарелла'           WHERE canonical_name = 'mozzarella';
UPDATE public.ingredients SET display_name_uz_cyrl = 'Пармезан'            WHERE canonical_name = 'parmesan';
UPDATE public.ingredients SET display_name_uz_cyrl = 'Сметана'             WHERE canonical_name = 'sour_cream';
UPDATE public.ingredients SET display_name_uz_cyrl = 'Табиий сут'          WHERE canonical_name = 'whole_milk';
UPDATE public.ingredients SET display_name_uz_cyrl = 'Қатиқ'              WHERE canonical_name = 'yogurt';
UPDATE public.ingredients SET display_name_uz_cyrl = 'Сузма'              WHERE canonical_name = 'suzma';
UPDATE public.ingredients SET display_name_uz_cyrl = 'Қурт'               WHERE canonical_name = 'kurt';
UPDATE public.ingredients SET display_name_uz_cyrl = 'Қаймоқ'             WHERE canonical_name = 'kaymak';
UPDATE public.ingredients SET display_name_uz_cyrl = 'Айрон'              WHERE canonical_name = 'ayran';
UPDATE public.ingredients SET display_name_uz_cyrl = 'Кефир'               WHERE canonical_name = 'kefir';
UPDATE public.ingredients SET display_name_uz_cyrl = 'Буттермилк'          WHERE canonical_name = 'buttermilk';
UPDATE public.ingredients SET display_name_uz_cyrl = 'Кокос сути'          WHERE canonical_name = 'coconut_milk';
UPDATE public.ingredients SET display_name_uz_cyrl = 'Маскарпоне'          WHERE canonical_name = 'mascarpone';
UPDATE public.ingredients SET display_name_uz_cyrl = 'Рикотта'             WHERE canonical_name = 'ricotta';
UPDATE public.ingredients SET display_name_uz_cyrl = 'Эчки пишлоқ'        WHERE canonical_name = 'goat_cheese';
UPDATE public.ingredients SET display_name_uz_cyrl = 'Тузсиз сариёғ'      WHERE canonical_name = 'unsalted_butter';
