-- ============================================================
-- I-Fridge — Seed: Extended Ingredients Part 4
-- ============================================================
-- ~260 additional ingredients covering world cuisines.
-- Includes Uzbek, Korean, Japanese, Mexican, Middle Eastern.
-- Uses ON CONFLICT to be safely re-runnable.
-- ============================================================

INSERT INTO public.ingredients
    (canonical_name, display_name_en, display_name_ko, category, default_unit,
     sealed_shelf_life_days, opened_shelf_life_days, storage_zone)
VALUES
    -- ── Vegetables (extended) ────────────────────────────────
    ('daikon',              'Daikon Radish',       '무',           'vegetable', 'piece',   14,   7,  'fridge'),
    ('beet',                'Beetroot',            '비트',         'vegetable', 'piece',   21,  10,  'fridge'),
    ('turnip',              'Turnip',              '순무',         'vegetable', 'piece',   21,  10,  'fridge'),
    ('radish',              'Radish',              '래디시',       'vegetable', 'piece',   14,   7,  'fridge'),
    ('kohlrabi',            'Kohlrabi',            '콜라비',       'vegetable', 'piece',   14,   7,  'fridge'),
    ('artichoke',           'Artichoke',           '아티초크',     'vegetable', 'piece',    7,   4,  'fridge'),
    ('fennel',              'Fennel',              '펜넬',         'vegetable', 'piece',   10,   5,  'fridge'),
    ('jicama',              'Jicama',              '히카마',       'vegetable', 'piece',   21,  10,  'fridge'),
    ('taro',                'Taro',                '토란',         'vegetable', 'piece',   14,   7,  'pantry'),
    ('cassava',             'Cassava',             '카사바',       'vegetable', 'piece',    7,   3,  'fridge'),
    ('parsnip',             'Parsnip',             '파스닙',       'vegetable', 'piece',   21,  10,  'fridge'),
    ('rutabaga',            'Rutabaga',            '루타바가',     'vegetable', 'piece',   30,  14,  'fridge'),
    ('endive',              'Endive',              '엔다이브',     'vegetable', 'piece',    7,   3,  'fridge'),
    ('watercress',          'Watercress',          '물냉이',       'vegetable', 'bunch',    5,   2,  'fridge'),
    ('bamboo_shoots',       'Bamboo Shoots',       '죽순',         'vegetable', 'g',      365,   5,  'pantry'),
    ('bean_sprouts',        'Bean Sprouts',        '숙주나물',     'vegetable', 'g',        3,   2,  'fridge'),
    ('snow_peas',           'Snow Peas',           '스노우피',     'vegetable', 'g',        5,   3,  'fridge'),
    ('water_chestnut',      'Water Chestnut',      '쪽파',         'vegetable', 'g',      365,   5,  'pantry'),
    ('brussels_sprouts',    'Brussels Sprouts',    '방울양배추',   'vegetable', 'g',       10,   5,  'fridge'),
    ('chard',               'Swiss Chard',         '근대',         'vegetable', 'bunch',    5,   3,  'fridge'),
    ('mustard_greens',      'Mustard Greens',      '겨자잎',       'vegetable', 'bunch',    5,   3,  'fridge'),
    ('collard_greens',      'Collard Greens',      '콜라드',       'vegetable', 'bunch',    7,   4,  'fridge'),

    -- ── Fruits (extended) ────────────────────────────────────
    ('fig',                 'Fig',                 '무화과',       'fruit',    'piece',    5,   3,  'fridge'),
    ('date',                'Date',                '대추',         'fruit',    'g',      180,  30,  'pantry'),
    ('persimmon',           'Persimmon',           '감',           'fruit',    'piece',    7,   5,  'fridge'),
    ('pomegranate',         'Pomegranate',         '석류',         'fruit',    'piece',   21,   5,  'fridge'),
    ('guava',               'Guava',               '구아바',       'fruit',    'piece',    5,   3,  'fridge'),
    ('passion_fruit',       'Passion Fruit',       '패션프루트',   'fruit',    'piece',   10,   5,  'fridge'),
    ('starfruit',           'Starfruit',           '스타프루트',   'fruit',    'piece',    7,   3,  'fridge'),
    ('papaya',              'Papaya',              '파파야',       'fruit',    'piece',    7,   3,  'fridge'),
    ('lychee',              'Lychee',              '리치',         'fruit',    'g',        7,   3,  'fridge'),
    ('dragon_fruit',        'Dragon Fruit',        '용과',         'fruit',    'piece',    5,   3,  'fridge'),
    ('rambutan',            'Rambutan',            '람부탄',       'fruit',    'g',        5,   3,  'fridge'),
    ('kumquat',             'Kumquat',             '금귤',         'fruit',    'g',       14,   7,  'fridge'),
    ('cranberry',           'Cranberry',           '크랜베리',     'fruit',    'g',       14,   7,  'fridge'),
    ('blackberry',          'Blackberry',          '블랙베리',     'fruit',    'g',        5,   3,  'fridge'),
    ('raspberry',           'Raspberry',           '라즈베리',     'fruit',    'g',        5,   3,  'fridge'),
    ('gooseberry',          'Gooseberry',          '구스베리',     'fruit',    'g',       14,   5,  'fridge'),
    ('plum',                'Plum',                '자두',         'fruit',    'piece',    7,   5,  'fridge'),
    ('apricot',             'Apricot',             '살구',         'fruit',    'piece',    5,   3,  'fridge'),
    ('nectarine',           'Nectarine',           '넥타린',       'fruit',    'piece',    5,   3,  'fridge'),
    ('quince',              'Quince',              '모과',         'fruit',    'piece',   30,  14,  'pantry'),
    ('tangerine',           'Tangerine',           '귤',           'fruit',    'piece',   14,   7,  'fridge'),
    ('clementine',          'Clementine',          '클레멘타인',   'fruit',    'piece',   14,   7,  'fridge'),
    ('dried_apricot',       'Dried Apricot',       '건살구',       'fruit',    'g',      180,  60,  'pantry'),
    ('raisin',              'Raisin',              '건포도',       'fruit',    'g',      365, 180,  'pantry'),
    ('dried_cranberry',     'Dried Cranberry',     '건크랜베리',   'fruit',    'g',      365, 180,  'pantry'),
    ('prune',               'Prune',               '푸룬',         'fruit',    'g',      180,  60,  'pantry'),

    -- ── Protein (extended) ───────────────────────────────────
    ('lamb',                'Lamb',                '양고기',       'protein',  'g',        5,   2,  'fridge'),
    ('lamb_shank',          'Lamb Shank',          '양갈비',       'protein',  'g',        5,   2,  'fridge'),
    ('duck',                'Duck',                '오리',         'protein',  'g',        3,   2,  'fridge'),
    ('rabbit',              'Rabbit',              '토끼고기',     'protein',  'g',        3,   2,  'fridge'),
    ('venison',             'Venison',             '사슴고기',     'protein',  'g',        5,   3,  'fridge'),
    ('quail',               'Quail',               '메추리',       'protein',  'g',        3,   2,  'fridge'),
    ('liver',               'Liver',               '간',           'protein',  'g',        2,   1,  'fridge'),
    ('ground_turkey',       'Ground Turkey',       '칠면조다짐',   'protein',  'g',        3,   1,  'fridge'),
    ('ground_pork',         'Ground Pork',         '돼지다짐',     'protein',  'g',        3,   1,  'fridge'),
    ('bacon',               'Bacon',               '베이컨',       'protein',  'g',       14,   7,  'fridge'),
    ('ham',                 'Ham',                 '햄',           'protein',  'g',       14,   5,  'fridge'),
    ('sausage',             'Sausage',             '소시지',       'protein',  'piece',   14,   5,  'fridge'),
    ('chorizo',             'Chorizo',             '초리조',       'protein',  'g',       21,   7,  'fridge'),
    ('salami',              'Salami',              '살라미',       'protein',  'g',       30,  14,  'fridge'),
    ('prosciutto',          'Prosciutto',          '프로슈토',     'protein',  'g',       60,   7,  'fridge'),
    ('horse_meat',          'Horse Meat',          '말고기',       'protein',  'g',        5,   2,  'fridge'),

    -- ── Seafood ──────────────────────────────────────────────
    ('salmon',              'Salmon',              '연어',         'seafood',  'g',        3,   2,  'fridge'),
    ('tuna',                'Tuna',                '참치',         'seafood',  'g',        2,   1,  'fridge'),
    ('cod',                 'Cod',                 '대구',         'seafood',  'g',        3,   2,  'fridge'),
    ('mackerel',            'Mackerel',            '고등어',       'seafood',  'g',        2,   1,  'fridge'),
    ('sardine',             'Sardine',             '정어리',       'seafood',  'g',        2,   1,  'fridge'),
    ('anchovy',             'Anchovy',             '멸치',         'seafood',  'g',      365,  30,  'pantry'),
    ('herring',             'Herring',             '청어',         'seafood',  'g',        2,   1,  'fridge'),
    ('tilapia',             'Tilapia',             '틸라피아',     'seafood',  'g',        3,   2,  'fridge'),
    ('shrimp',              'Shrimp',              '새우',         'seafood',  'g',        3,   1,  'fridge'),
    ('crab',                'Crab',                '게',           'seafood',  'g',        2,   1,  'fridge'),
    ('lobster',             'Lobster',             '랍스터',       'seafood',  'g',        2,   1,  'fridge'),
    ('mussel',              'Mussel',              '홍합',         'seafood',  'g',        2,   1,  'fridge'),
    ('oyster',              'Oyster',              '굴',           'seafood',  'piece',    2,   1,  'fridge'),
    ('clam',                'Clam',                '조개',         'seafood',  'g',        2,   1,  'fridge'),
    ('scallop',             'Scallop',             '가리비',       'seafood',  'g',        2,   1,  'fridge'),
    ('squid',               'Squid',               '오징어',       'seafood',  'g',        2,   1,  'fridge'),
    ('octopus',             'Octopus',             '문어',         'seafood',  'g',        2,   1,  'fridge'),
    ('canned_tuna',         'Canned Tuna',         '참치캔',       'seafood',  'g',      730,   3,  'pantry'),
    ('dried_shrimp',        'Dried Shrimp',        '건새우',       'seafood',  'g',      365,  60,  'pantry'),
    ('fish_sauce',          'Fish Sauce',          '피쉬소스',     'condiment','ml',      730, 365,  'pantry'),

    -- ── Dairy (extended) ─────────────────────────────────────
    ('cream_cheese',        'Cream Cheese',        '크림치즈',     'dairy',    'g',       30,  14,  'fridge'),
    ('ricotta',             'Ricotta',             '리코타',       'dairy',    'g',        7,   3,  'fridge'),
    ('mascarpone',          'Mascarpone',          '마스카포네',   'dairy',    'g',       14,   5,  'fridge'),
    ('feta',                'Feta Cheese',         '페타치즈',     'dairy',    'g',       60,  14,  'fridge'),
    ('gouda',               'Gouda Cheese',        '고다치즈',     'dairy',    'g',       90,  21,  'fridge'),
    ('brie',                'Brie Cheese',         '브리치즈',     'dairy',    'g',       14,   7,  'fridge'),
    ('cottage_cheese',      'Cottage Cheese',      '코티지치즈',   'dairy',    'g',       14,   5,  'fridge'),
    ('sour_cream',          'Sour Cream',          '사워크림',     'dairy',    'g',       21,  10,  'fridge'),
    ('whipping_cream',      'Whipping Cream',      '생크림',       'dairy',    'ml',      14,   5,  'fridge'),
    ('condensed_milk',      'Condensed Milk',      '연유',         'dairy',    'ml',     365,  14,  'pantry'),
    ('evaporated_milk',     'Evaporated Milk',     '무가당연유',   'dairy',    'ml',     365,   5,  'pantry'),
    ('yogurt_plain',        'Plain Yogurt',        '플레인요거트', 'dairy',    'g',       14,   5,  'fridge'),
    ('greek_yogurt',        'Greek Yogurt',        '그릭요거트',   'dairy',    'g',       14,   5,  'fridge'),
    ('kefir',               'Kefir',               '케피르',       'dairy',    'ml',      14,   7,  'fridge'),
    ('ghee',                'Ghee',                '기',           'dairy',    'g',      365, 180,  'pantry'),

    -- ── Central Asian / Uzbek ────────────────────────────────
    ('cumin',               'Cumin',               '커민',         'spice',    'tsp',    730, 365,  'pantry'),
    ('turmeric',            'Turmeric',            '강황',         'spice',    'tsp',    730, 365,  'pantry'),
    ('coriander_seed',      'Coriander Seeds',     '고수씨',       'spice',    'tsp',    730, 365,  'pantry'),
    ('paprika',             'Paprika',             '파프리카가루', 'spice',    'tsp',    730, 365,  'pantry'),
    ('chili_flakes',        'Chili Flakes',        '고추플레이크', 'spice',    'tsp',    730, 365,  'pantry'),
    ('bay_leaf',            'Bay Leaf',            '월계수잎',     'spice',    'piece',  730, 365,  'pantry'),
    ('dill',                'Dill',                '딜',           'herb',     'bunch',    7,   3,  'fridge'),
    ('cilantro',            'Cilantro',            '고수',         'herb',     'bunch',    7,   3,  'fridge'),
    ('parsley',             'Parsley',             '파슬리',       'herb',     'bunch',    7,   3,  'fridge'),
    ('mint',                'Mint',                '민트',         'herb',     'bunch',    7,   3,  'fridge'),
    ('basil',               'Basil',               '바질',         'herb',     'bunch',    7,   3,  'fridge'),
    ('rosemary',            'Rosemary',            '로즈마리',     'herb',     'bunch',   10,   5,  'fridge'),
    ('thyme',               'Thyme',               '타임',         'herb',     'bunch',   10,   5,  'fridge'),
    ('oregano_dried',       'Dried Oregano',       '오레가노',     'spice',    'tsp',    730, 365,  'pantry'),
    ('sumac',               'Sumac',               '수막',         'spice',    'tsp',    365, 180,  'pantry'),
    ('saffron',             'Saffron',             '샤프란',       'spice',    'pinch',  730, 365,  'pantry'),
    ('cardamom',            'Cardamom',            '카다몬',       'spice',    'piece',  730, 365,  'pantry'),
    ('clove',               'Clove',               '정향',         'spice',    'piece',  730, 365,  'pantry'),
    ('cinnamon',            'Cinnamon',            '시나몬',       'spice',    'tsp',    730, 365,  'pantry'),
    ('nutmeg',              'Nutmeg',              '넛맥',         'spice',    'tsp',    730, 365,  'pantry'),
    ('fenugreek',           'Fenugreek',           '호로파',       'spice',    'tsp',    730, 365,  'pantry'),
    ('barberry',            'Barberry',            '매자나무열매', 'spice',    'g',      365, 180,  'pantry'),
    ('chickpeas',           'Chickpeas',           '병아리콩',     'legume',   'g',      365,   5,  'pantry'),
    ('mung_beans',          'Mung Beans',          '녹두',         'legume',   'g',      365,   5,  'pantry'),
    ('black_beans',         'Black Beans',         '검은콩',       'legume',   'g',      365,   5,  'pantry'),
    ('kidney_beans',        'Kidney Beans',        '강낭콩',       'legume',   'g',      365,   5,  'pantry'),
    ('white_beans',         'White Beans',         '흰콩',         'legume',   'g',      365,   5,  'pantry'),
    ('split_peas',          'Split Peas',          '스플릿피',     'legume',   'g',      365,   5,  'pantry'),

    -- ── Grains & Noodles (extended) ──────────────────────────
    ('basmati_rice',        'Basmati Rice',        '바스마티쌀',   'grain',    'cup',    365, 180,  'pantry'),
    ('jasmine_rice',        'Jasmine Rice',        '자스민쌀',     'grain',    'cup',    365, 180,  'pantry'),
    ('sticky_rice',         'Sticky Rice',         '찹쌀',         'grain',    'cup',    365, 180,  'pantry'),
    ('brown_rice',          'Brown Rice',          '현미',         'grain',    'cup',    180,  90,  'pantry'),
    ('quinoa',              'Quinoa',              '퀴노아',       'grain',    'cup',    365, 180,  'pantry'),
    ('couscous',            'Couscous',            '쿠스쿠스',     'grain',    'cup',    365, 180,  'pantry'),
    ('bulgur',              'Bulgur',              '불구르',       'grain',    'cup',    365, 180,  'pantry'),
    ('buckwheat',           'Buckwheat',           '메밀',         'grain',    'cup',    365, 180,  'pantry'),
    ('oat',                 'Oats',                '귀리',         'grain',    'cup',    365, 180,  'pantry'),
    ('barley',              'Barley',              '보리',         'grain',    'cup',    365, 180,  'pantry'),
    ('millet',              'Millet',              '수수',         'grain',    'cup',    365, 180,  'pantry'),
    ('cornmeal',            'Cornmeal',            '옥수수가루',   'grain',    'cup',    365, 180,  'pantry'),
    ('polenta',             'Polenta',             '폴렌타',       'grain',    'cup',    365, 180,  'pantry'),
    ('soba_noodles',        'Soba Noodles',        '소바면',       'grain',    'g',      365, 180,  'pantry'),
    ('udon_noodles',        'Udon Noodles',        '우동면',       'grain',    'g',      365,   3,  'pantry'),
    ('ramen_noodles',       'Ramen Noodles',       '라면',         'grain',    'g',      365, 180,  'pantry'),
    ('rice_noodles',        'Rice Noodles',        '쌀국수면',     'grain',    'g',      365, 180,  'pantry'),
    ('egg_noodles',         'Egg Noodles',         '계란면',       'grain',    'g',      365, 180,  'pantry'),
    ('pita_bread',          'Pita Bread',          '피타빵',       'grain',    'piece',    7,   3,  'pantry'),
    ('tortilla',            'Tortilla',            '토르티야',     'grain',    'piece',   14,   5,  'fridge'),
    ('naan',                'Naan Bread',          '난',           'grain',    'piece',    5,   2,  'pantry'),
    ('lavash',              'Lavash',              '라바쉬',       'grain',    'piece',    7,   3,  'pantry'),
    ('non_bread',           'Non (Uzbek Bread)',   '논빵',         'grain',    'piece',    3,   1,  'pantry'),

    -- ── Condiments & Sauces (extended) ───────────────────────
    ('oyster_sauce',        'Oyster Sauce',        '굴소스',       'condiment','ml',      365, 180,  'pantry'),
    ('hoisin_sauce',        'Hoisin Sauce',        '호이신소스',   'condiment','ml',      365, 180,  'pantry'),
    ('sriracha',            'Sriracha Sauce',      '스리라차',     'condiment','ml',      730, 365,  'pantry'),
    ('teriyaki_sauce',      'Teriyaki Sauce',      '데리야끼소스', 'condiment','ml',      365, 180,  'pantry'),
    ('worcestershire',      'Worcestershire',      '우스터소스',   'condiment','ml',      730, 365,  'pantry'),
    ('tabasco',             'Tabasco',             '타바스코',     'condiment','ml',     1825, 365,  'pantry'),
    ('balsamic_vinegar',    'Balsamic Vinegar',    '발사믹식초',   'condiment','ml',      730, 365,  'pantry'),
    ('rice_vinegar',        'Rice Vinegar',        '쌀식초',       'condiment','ml',      730, 365,  'pantry'),
    ('apple_cider_vinegar', 'Apple Cider Vinegar', '사과식초',     'condiment','ml',     1825,1825,  'pantry'),
    ('mustard',             'Mustard',             '머스타드',     'condiment','tsp',     365, 180,  'fridge'),
    ('dijon_mustard',       'Dijon Mustard',       '디종머스타드', 'condiment','tsp',     365, 180,  'fridge'),
    ('ketchup',             'Ketchup',             '케찹',         'condiment','ml',      365, 180,  'fridge'),
    ('mayonnaise',          'Mayonnaise',          '마요네즈',     'condiment','ml',      180,  60,  'fridge'),
    ('tahini',              'Tahini',              '타히니',       'condiment','g',       365, 180,  'pantry'),
    ('miso_paste',          'Miso Paste',          '된장',         'condiment','g',       365, 180,  'fridge'),
    ('gochujang',           'Gochujang',           '고추장',       'condiment','g',       365, 180,  'fridge'),
    ('doenjang',            'Doenjang',            '된장',         'condiment','g',       365, 180,  'fridge'),
    ('sambal',              'Sambal Oelek',        '삼발소스',     'condiment','g',       365, 180,  'fridge'),
    ('tamarind_paste',      'Tamarind Paste',      '타마린드페이스트', 'condiment','g',   365, 180,  'pantry'),
    ('pomegranate_molasses', 'Pomegranate Molasses', '석류시럽',   'condiment','ml',      365, 180,  'pantry'),
    ('harissa',             'Harissa',             '하리사',       'condiment','g',       365, 180,  'fridge'),
    ('pesto',               'Pesto',               '페스토',       'condiment','g',        7,   5,  'fridge'),

    -- ── Oils & Fats ──────────────────────────────────────────
    ('olive_oil',           'Olive Oil',           '올리브유',     'oil',      'ml',     730, 365,  'pantry'),
    ('sesame_oil',          'Sesame Oil',          '참기름',       'oil',      'ml',     365, 180,  'pantry'),
    ('coconut_oil',         'Coconut Oil',         '코코넛오일',   'oil',      'ml',     730, 365,  'pantry'),
    ('avocado_oil',         'Avocado Oil',         '아보카도오일', 'oil',      'ml',     365, 180,  'pantry'),
    ('sunflower_oil',       'Sunflower Oil',       '해바라기유',   'oil',      'ml',     365, 180,  'pantry'),
    ('canola_oil',          'Canola Oil',          '카놀라유',     'oil',      'ml',     365, 180,  'pantry'),
    ('lard',                'Lard',                '라드',         'oil',      'g',      180,  90,  'fridge'),
    ('cottonseed_oil',      'Cottonseed Oil',       '면실유',       'oil',      'ml',     365, 180,  'pantry'),

    -- ── Baking (extended) ────────────────────────────────────
    ('baking_powder',       'Baking Powder',       '베이킹파우더', 'baking',   'tsp',    365, 180,  'pantry'),
    ('yeast',               'Active Dry Yeast',    '이스트',       'baking',   'tsp',    365,  14,  'pantry'),
    ('cornstarch',          'Cornstarch',          '옥수수전분',   'baking',   'tbsp',   730, 365,  'pantry'),
    ('gelatin',             'Gelatin',             '젤라틴',       'baking',   'g',      365, 180,  'pantry'),
    ('cocoa_powder',        'Cocoa Powder',        '코코아파우더', 'baking',   'tbsp',   730, 365,  'pantry'),
    ('vanilla_extract',     'Vanilla Extract',     '바닐라엑기스', 'baking',   'tsp',    730, 365,  'pantry'),
    ('almond_extract',      'Almond Extract',      '아몬드엑기스', 'baking',   'tsp',    730, 365,  'pantry'),
    ('powdered_sugar',      'Powdered Sugar',      '슈가파우더',   'baking',   'cup',    730, 365,  'pantry'),
    ('brown_sugar',         'Brown Sugar',         '흑설탕',       'baking',   'cup',    730, 365,  'pantry'),
    ('honey',               'Honey',               '꿀',           'baking',   'tbsp',  1825, 365,  'pantry'),
    ('maple_syrup',         'Maple Syrup',         '매이플시럽',   'baking',   'tbsp',   365, 180,  'pantry'),
    ('molasses',            'Molasses',            '당밀',         'baking',   'tbsp',   365, 180,  'pantry'),
    ('chocolate_chips',     'Chocolate Chips',     '초콜릿칩',     'baking',   'g',      365, 180,  'pantry'),
    ('dark_chocolate',      'Dark Chocolate',      '다크초콜릿',   'baking',   'g',      365, 180,  'pantry'),
    ('white_chocolate',     'White Chocolate',     '화이트초콜릿', 'baking',   'g',      365, 180,  'pantry'),
    ('bread_flour',         'Bread Flour',         '강력분',       'baking',   'cup',    365, 180,  'pantry'),
    ('cake_flour',          'Cake Flour',          '박력분',       'baking',   'cup',    365, 180,  'pantry'),
    ('almond_flour',        'Almond Flour',        '아몬드가루',   'baking',   'cup',    180,  90,  'pantry'),
    ('coconut_flour',       'Coconut Flour',       '코코넛가루',   'baking',   'cup',    365, 180,  'pantry'),

    -- ── Nuts & Seeds ─────────────────────────────────────────
    ('almond',              'Almond',              '아몬드',       'nut',      'g',      365, 180,  'pantry'),
    ('walnut',              'Walnut',              '호두',         'nut',      'g',      365, 180,  'pantry'),
    ('cashew',              'Cashew',              '캐슈넛',       'nut',      'g',      365, 180,  'pantry'),
    ('pistachio',           'Pistachio',           '피스타치오',   'nut',      'g',      365, 180,  'pantry'),
    ('peanut',              'Peanut',              '땅콩',         'nut',      'g',      365, 180,  'pantry'),
    ('pecan',               'Pecan',               '피칸',         'nut',      'g',      365, 180,  'pantry'),
    ('hazelnut',            'Hazelnut',            '헤이즐넛',     'nut',      'g',      365, 180,  'pantry'),
    ('macadamia',           'Macadamia Nut',       '마카다미아',   'nut',      'g',      365, 180,  'pantry'),
    ('pine_nut',            'Pine Nut',            '잣',           'nut',      'g',      180,  90,  'pantry'),
    ('sesame_seeds',        'Sesame Seeds',        '참깨',         'nut',      'tsp',    365, 180,  'pantry'),
    ('sunflower_seeds',     'Sunflower Seeds',     '해바라기씨',   'nut',      'g',      365, 180,  'pantry'),
    ('pumpkin_seeds',       'Pumpkin Seeds',       '호박씨',       'nut',      'g',      365, 180,  'pantry'),
    ('chia_seeds',          'Chia Seeds',          '치아씨',       'nut',      'g',      730, 365,  'pantry'),
    ('flax_seeds',          'Flax Seeds',          '아마씨',       'nut',      'g',      365, 180,  'pantry'),
    ('hemp_seeds',          'Hemp Seeds',          '헴프씨',       'nut',      'g',      365, 180,  'pantry'),
    ('poppy_seeds',         'Poppy Seeds',         '양귀비씨',     'nut',      'g',      365, 180,  'pantry'),
    ('peanut_butter',       'Peanut Butter',       '땅콩버터',     'nut',      'g',      365, 180,  'pantry'),
    ('almond_butter',       'Almond Butter',       '아몬드버터',   'nut',      'g',      365, 180,  'pantry'),
    ('tahini_paste',        'Tahini Paste',        '타히니',       'nut',      'g',      365, 180,  'pantry'),

    -- ── Beverages & Liquids ──────────────────────────────────
    ('coconut_milk',        'Coconut Milk',        '코코넛밀크',   'beverage', 'ml',     365,   5,  'pantry'),
    ('almond_milk',         'Almond Milk',         '아몬드밀크',   'beverage', 'ml',      60,   7,  'fridge'),
    ('oat_milk',            'Oat Milk',            '오트밀크',     'beverage', 'ml',      60,   7,  'fridge'),
    ('soy_milk',            'Soy Milk',            '두유',         'beverage', 'ml',      60,   7,  'fridge'),
    ('green_tea',           'Green Tea',           '녹차',         'beverage', 'g',      365, 180,  'pantry'),
    ('black_tea',           'Black Tea',           '홍차',         'beverage', 'g',      730, 365,  'pantry'),
    ('matcha',              'Matcha Powder',       '말차',         'beverage', 'g',      365, 180,  'pantry'),

    -- ── Tofu & Plant-Based ───────────────────────────────────
    ('tofu_firm',           'Firm Tofu',           '두부',         'protein',  'g',        7,   3,  'fridge'),
    ('tofu_silken',         'Silken Tofu',         '순두부',       'protein',  'g',        7,   3,  'fridge'),
    ('tempeh',              'Tempeh',              '템페',         'protein',  'g',       10,   5,  'fridge'),
    ('seitan',              'Seitan',              '세이탄',       'protein',  'g',        7,   3,  'fridge'),

    -- ── Canned / Preserved ───────────────────────────────────
    ('canned_tomato',       'Canned Tomatoes',     '토마토캔',     'canned',   'g',      730,   5,  'pantry'),
    ('canned_corn',         'Canned Corn',         '옥수수캔',     'canned',   'g',      730,   3,  'pantry'),
    ('canned_beans',        'Canned Beans',        '콩캔',         'canned',   'g',      730,   3,  'pantry'),
    ('canned_coconut_milk', 'Canned Coconut Milk', '코코넛밀크캔', 'canned',   'ml',     730,   5,  'pantry'),
    ('tomato_sauce',        'Tomato Sauce',        '토마토소스',   'canned',   'ml',     730,   5,  'pantry'),
    ('broth_chicken',       'Chicken Broth',       '닭육수',       'canned',   'ml',     365,   5,  'pantry'),
    ('broth_beef',          'Beef Broth',          '소고기육수',   'canned',   'ml',     365,   5,  'pantry'),
    ('broth_vegetable',     'Vegetable Broth',     '야채육수',     'canned',   'ml',     365,   5,  'pantry'),
    ('pickled_cucumber',    'Pickled Cucumber',    '오이피클',     'canned',   'piece',  365,  30,  'fridge'),
    ('kimchi',              'Kimchi',              '김치',         'canned',   'g',       90,  30,  'fridge'),
    ('sauerkraut',          'Sauerkraut',          '사워크라우트', 'canned',   'g',      180,  14,  'fridge'),
    ('olives',              'Olives',              '올리브',       'canned',   'g',      365,  14,  'fridge'),
    ('capers',              'Capers',              '케이퍼',       'canned',   'g',      365,  14,  'fridge'),
    ('sun_dried_tomato',    'Sun-Dried Tomatoes',  '건조토마토',   'canned',   'g',      365,  14,  'pantry'),
    ('coconut_cream',       'Coconut Cream',       '코코넛크림',   'canned',   'ml',     730,   5,  'pantry')

ON CONFLICT (canonical_name) DO UPDATE SET
    display_name_en        = EXCLUDED.display_name_en,
    display_name_ko        = EXCLUDED.display_name_ko,
    category               = EXCLUDED.category,
    default_unit           = EXCLUDED.default_unit,
    sealed_shelf_life_days = EXCLUDED.sealed_shelf_life_days,
    opened_shelf_life_days = EXCLUDED.opened_shelf_life_days,
    storage_zone           = EXCLUDED.storage_zone;
