import json
import asyncio
import sys

sys.path.insert(0, r'd:\dev\projects\iFridge\backend')
from dotenv import load_dotenv
load_dotenv(r'd:\dev\projects\iFridge\backend\.env')
from app.db.supabase_client import get_supabase

async def main():
    db = get_supabase()
    
    # Get currently successfully generated recipes
    resp = db.table("recipes").select("id").neq("ingredients", "[]").execute()
    success_ids = {r["id"] for r in resp.data}
    
    print(f"Found {len(success_ids)} recipes successfully generated by Ollama.")
    print("Restoring the rest from backup...")
    
    try:
        with open("recipes_backup.json", "r", encoding="utf-8") as f:
            backup = json.load(f)
    except Exception as e:
        print(f"Failed to load backup: {e}")
        return
        
    restored = 0
    for r in backup:
        if r["id"] not in success_ids:
            db.table("recipes").update({
                "ingredients": r.get("ingredients", []),
                "steps": r.get("steps", [])
            }).eq("id", r["id"]).execute()
            restored += 1
            
    print(f"Successfully restored {restored} recipes into the new JSONB format!")

if __name__ == "__main__":
    asyncio.run(main())
